name: Bug反馈  
description: 创建报告以帮助我们改进  
labels: ["Bug"]

body:  
  - type: markdown  
    attributes:  
      value: |  
        请填写下面的所有字段。  
  
  - type: textarea  
    id: description-of-bug  
    attributes:  
      label: 描述Bug  
      description: 清晰简洁地描述这个Bug是什么。  
    validations:  
      required: true  
  
  - type: textarea  
    id: steps-to-reproduce  
    attributes:  
      label: 重现步骤  
      description: 重现这个Bug的步骤。  
    validations:  
      required: true 
  
  - type: textarea  
    id: expected-behavior  
    attributes:  
      label: 预期行为  
      description: 清晰简洁地描述你期望发生什么。   
    validations:  
      required: true
  
  - type: textarea  
    id: screenshots  
    attributes:  
      label: 截图  
    validations:  
      required: true

 - type: textarea  
    id: save-file  
    attributes:  
      label: 上传存档文件  
      description: |  
        `调试菜单 ->信息 ->生成最小化存档   
    validations:  
      required: true  

 - type: textarea  
    id: versions-and-config  
    attributes:  
      label: 版本和系统  
      placeholder: |  
        - 操作系统： 
        - 游戏版本： 
        - 已加载的模组：
    validations:  
      required: true